# Generated by Django 3.2.9 on 2021-12-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='fatherId',
            new_name='replyUserId',
        ),
        migrations.RemoveField(
            model_name='category',
            name='fatherId',
        ),
        migrations.AddField(
            model_name='comments',
            name='replyUserName',
            field=models.CharField(default='未知用户', max_length=100),
        ),
        migrations.AlterField(
            model_name='articles',
            name='commentNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='readNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='upvoteNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='upvoteNum',
            field=models.IntegerField(default=0),
        ),
    ]
